
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.2.0-beta{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

# clone directory
clone_folder: c:\projects\Eowin.AzureServiceBusRelay.Server

environment:
  ServiceBusAddress:
    secure: cv7TOmQc18UZ+mqPvK55WD+ulvts8qKWa/3JTca5WfQLmbV+OSXDcsx/1mMfTnsLSVO6jPlPm9WM7mITC4fHAA==
  ServiceBusSecret:
    secure: +DZooOkqXvlcW/gOLCJzhX9pzrtHIgnHrtRDu30zFvq4cWvEdzh2IC84DezhNSpz


# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.2.0"
  assembly_file_version: "0.2.0"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
- nuget restore src\Eowin.AzureServiceBusRelay.sln

build:
  project: src\Eowin.AzureServiceBusRelay.sln
  publish_nuget: true

# to disable automatic builds
#build: off

#---------------------------------#
#       tests configuration       #
#---------------------------------#

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts: []

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  provider: NuGet  
  api_key:
    secure: RBbVRxtACiB2I4L0VSgWVx8Tf/L6HsA5rHVFFrdUvOnHWUSopbrqaBzsFr+Y7tT7
  artifact: /.*\.nupkg/
  on:
    branch: release

#---------------------------------#
#        global handlers          #
#---------------------------------#

#---------------------------------#
#         notifications           #
#---------------------------------#
